cluster.name: kubernetes-logging

node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}
node.name: ${HOSTNAME}

bootstrap.mlockall: ${BOOTSTRAP_MLOCKALL}

network.host: 0.0.0.0
transport.tcp.port: ${TRANSPORT_PORT}
http.port: ${HTTP_PORT}

cloud:
  kubernetes:
    service: ${SERVICE}
    namespace: ${KUBERNETES_NAMESPACE}

discovery:
  type: kubernetes
  zen:
    minimum_master_nodes: 2
    ping:
      multicast:
        enabled: false

path:
  plugins: /usr/share/elasticsearch/plugins
  data: /data
